### ISSUE TITLE
Listing Directories doesn't work

### ISSUE THREAD

**Issue by jedlikowski** [PlatformCommunity/flysystem-bunnycdn#12]
Hi guys, it's me again :) Last time I was trying to delete a directory, now I'm trying to list directories inside a directory. The case is I have a folder which contains a bunch of other folders:
```
sites/
├─ inner folder 1/
├─ inner folder 2/
├─ ... etc
```

I'm trying to get a list of folders inside `sites` folder but I get an empty array when running the following code even though there should be tons of folders there:
```php
$directories = $disk->directories('sites');
```

I've managed to trace and fix this bug locally. And I'm happy to create a PR with the fix but want to get your opinions about it first.

What is the issue?
When listing directories, the results of `listContents()` from the adapter are passed to `\League\Flysystem\Util\ContentListingFormatter@formatListing`. This formatter filters the list using, among others, this piece of code:
```php
$entry['dirname'] === $this->directory
```
Source: https://github.com/thephpleague/flysystem/blob/1.x/src/Util/ContentListingFormatter.php#L64

And the "dirname" of each entry returned from adapter looks like this: `/sites/`. Obviously `"/sites/"  !==  "sites"` which is why each folder is deemed out of range.

A fix would be to change the `PlatformCommunity\Flysystem\BunnyCDN\BunnyCDNAdapter@normalizeObject` a bit from this:
```php
'dirname' => $this->removePathPrefix($fileObject->Path),
```

to this:
```php
'dirname' => trim($this->removePathPrefix($fileObject->Path), "/"),
```

But not sure if this would be a breaking change maybe? What do you guys think?

**Comment by jedlikowski** [comment]
@sifex Is there any possibility to move forward with this? Haha, sorry to push you but we are experiencing it in production. It causes the CDN cleanup function to not run correctly.

**Comment by sifex** [comment]
Hey @jedlikowski, merged and release made.

In future, I'd suggest to not have to wait on maintainers on smaller packages like this, should be able to source from your fork in `composer.json`.

See: https://stackoverflow.com/a/14485706/15375077
