### ISSUE TITLE
BunnyCDN does not support steam writing

### ISSUE THREAD

**Issue by MrMooky** [PlatformCommunity/flysystem-bunnycdn#14]
When uploading a file, I get:

> League\Flysystem\NotSupportedException: BunnyCDN does not support steam writing, use -&gt;write() instead in file /Users/xxx/Code/xxx/vendor/platformcommunity/flysystem-bunnycdn/src/BunnyCDNAdapter.php on line 75

**Comment by sifex** [comment]
This should now be fixed by #11, please let me know if this fixes it for you 😊

**Comment by MrMooky** [comment]
I just installed the package again, set up everything and wanted to give the PR a shot. But now, a simple `Storage::url('users/avatars/'.$user->avatar)` returns the following error:

```
This driver does not support retrieving URLs.
```

**Comment by sifex** [comment]
@MrMooky hmmmm, this seems to require a pull zone configuration, I'll have a look into this now

**Comment by sifex** [comment]
Hey @MrMooky, I've release v1.1.1 which should fix your issue.

You'll need to add the `pullzone_url` parameter to your Storage Adapter, I've updated the README with instructions on how to complete that.

**Comment by MrMooky** [comment]
That fixed it! Thank you very much. Everything (uploading, retrieving and deleting) seems to work now. 🎈
