### ISSUE TITLE
Crash in normalizeObject

### ISSUE THREAD

**Issue by jedlikowski** [PlatformCommunity/flysystem-bunnycdn#21]
Hi guys,
I'm using v1.3.0 of your library at the moment. Looks like a crash appears sometimes in `normalizeObject` method of `BunnyCDNAdapter` class which produces this exception: `Call to a member function getTimestamp() on bool`. We only noticed it in production due to the sheer amount of files we are processing there.

After adding some logs to the class I found out that Bunny API sometimes returns file change and creation timestamps in the format you expect (e.g. `2022-04-10T17:43:49.297`) but sometimes the fractional seconds are missing: `2022-04-10T16:40:48`. When fractional seconds are missing, the code crashes because the DateTime object can't be created from format and `date_create_from_format` returns `false`.

Could you find a fix for this issue? We already contacted the bunny team too to standarize the timestamps a bit more but the issue is quite urgent for us hence the ticket here too. :)

**Comment by jedlikowski** [comment]
Thanks 👍  I had to perform a dirty quickfix directly in the vendor folder with a piece of code like this:

```php
if (strpos($bunny_file_array["LastChanged"], ".") === false) {
  $bunny_file_array["LastChanged"] .= ".000";
}
if (strpos($bunny_file_array["DateCreated"], ".") === false) {
  $bunny_file_array["DateCreated"] .= ".000";
}
```

**Comment by jedlikowski** [comment]
@sifex Hi, how was breakfast? 😁

**Comment by sifex** [comment]
> @sifex Hi, how was breakfast? 😁

Hey sorry, I'm currently traveling and working on this in my spare time. Pushed a [new version (v1.3.1)](https://packagist.org/packages/platformcommunity/flysystem-bunnycdn#v1.3.1) that should resolve the issue. Please let me know if it doesn't.

**Comment by sifex** [comment]
Should also mention that v1 will stop getting support soon, as Flysystem v2 and v3 are becoming the default standard going forward.

**Comment by jedlikowski** [comment]
Of course. We should upgrade our project to Laravel 9 in the near future anyway, so Flysystem v2 support should come with that.
