### ISSUE TITLE
features + fixes

### ISSUE THREAD

**Issue by tinect** [PlatformCommunity/flysystem-bunnycdn#33]
Hey there,

thank you for the project!!! :-)

I have a few things which seems not to have finished yet.
I'll try to support by PR next days. 

- [ ] readStream should throw UnableToReadFile, not BunnyCDNException or NotFoundException
- [ ] listContents with deep should be supported
- [ ] possibility to specify root-directory/prefix-path

**Comment by ben182** [comment]
#30 #32

**Comment by ben182** [comment]
@sifex can you have a look at the PRs?

**Comment by sifex** [comment]
v3.2.0 Tagged and released ❤️ Thanks @tinect

**Comment by ben182** [comment]
Thanks @sifex, can you have a look at the packagist / GitHub webhook config? Seems like there is an issue with auto updating to the latest tagged version

**Comment by sifex** [comment]
Nice catch, fixed up now
