### ISSUE TITLE
Can't request file containing json

### ISSUE THREAD

**Issue by stefanpoensgen** [PlatformCommunity/flysystem-bunnycdn#39]
If you request a file which contains json, it gets decoded as array.

https://github.com/PlatformCommunity/flysystem-bunnycdn/blob/9bf9e090d7c0b095c908aec458a38971aad49e46/src/BunnyCDNClient.php#L46-L62

**Comment by sifex** [comment]
I'll have a look at this one on the flight ❤️ thanks for raising it

**Comment by sifex** [comment]
#40
