### ISSUE TITLE
Update the BunnyCDN library

### ISSUE THREAD

**Issue by GeertHauwaerts** [PlatformCommunity/flysystem-bunnycdn#4]
Hey @sifex, BunnyCDN added storage zone locations (default to `de`) into [it's library](https://github.com/BunnyWay/BunnyCDN.PHP.Storage). Can you pull the changes from the parent?

> Note: I opened the issue here since [PlatformCommunity/BunnyCDN.PHP.Storage](https://github.com/PlatformCommunity/BunnyCDN.PHP.Storage) does not allow new issues; my apologies for the cross-post.

**Comment by sifex** [comment]
> Can you pull the changes from the parent?

Haha, sure, I'm not sure what state the upstream is in though :P

**Comment by sifex** [comment]
Using flysystem as a validation, looks like everything it working as expected.
