### ISSUE TITLE
[FEATURE] Use path-prefixing instead of own implementation

### ISSUE THREAD

**Issue by tinect** [PlatformCommunity/flysystem-bunnycdn#47]
https://flysystem.thephpleague.com/docs/adapter/path-prefixing/

Came with 3.3 :-)

**Comment by sifex** [comment]
Oooohh I'm gonna quickly jot home after dinner and take a look at this one

**Comment by tinect** [comment]
Great.
The best solution seems to be to remove it entire from this repo, isn't it? :-(

So much time invested... and the guy I'm talking daily just created specific PR at flysystem meanwhile 😆

**Comment by tinect** [comment]
First Tests: Looks good!

The only test regarding prefix-path is this: https://github.com/PlatformCommunity/flysystem-bunnycdn/blob/cb9f07698aeffa4ff424d58971a35c956da22b10/tests/FlysystemTestSuite.php#L249-L252

But this seems wrong, too.
