### ISSUE TITLE
Upgrade to guzzlehttp/guzzle ^7.0

### ISSUE THREAD

**Issue by connecteev** [PlatformCommunity/flysystem-bunnycdn#5]
Could we upgrade this package to require the latest version of guzzle, v 7.0.ie "guzzlehttp/guzzle": "^7.0"

I am trying to resolve this issue: https://github.com/composer/composer/issues/9306
and am seeing conflicts because of different minimum required versions of guzzle.

**Comment by stof** [comment]
The easy fix for that is to remove the dependency. guzzle is not used. See my PR.

**Comment by connecteev** [comment]
@stof thank you for looking into this and the PR. 
tagging @sifex so this can hopefully get merged in.

**Comment by sifex** [comment]
Thanks for picking this one up @connecteev, merged. Added the `hacktoberfest-accepted` label for you as well

**Comment by connecteev** [comment]
Thank you @sifex ! How does the `hacktoberfest-accepted` work btw? Just curious and Happy hacktoberfest  :)

**Comment by sifex** [comment]
The hacktoberfest initiative flooded many open source projects with dummy PRs, so they implimented a label-based approach for repo owners to approve what's considered a proper "hacktoberfest" contribution.

https://hacktoberfest.digitalocean.com/

**Comment by connecteev** [comment]
Got it! Btw - I imagine I should use `"platformcommunity/flysystem-bunnycdn": "dev-master"` instead of `"platformcommunity/flysystem-bunnycdn": "^0.3.0",` or until 0.3.1 gets released....
