### ISSUE TITLE
Deleting directories doesn't work

### ISSUE THREAD

**Issue by jedlikowski** [PlatformCommunity/flysystem-bunnycdn#8]
Hi,
I've noticed that folders aren't being deleted from my storage zone and I've tracked it down to a path issue. When performing a DELETE request for a folder, BunnyCDN API returns 404 if path doesn't end with `/`.
See my two requests below done via the Insomnia app:

<img width="1219" alt="Zrzut ekranu 2021-02-24 o 16 09 31" src="https://user-images.githubusercontent.com/9341608/109168630-4fe6a680-777f-11eb-989d-b8524d1d16c0.png">
 
<img width="1317" alt="Zrzut ekranu 2021-02-25 o 15 25 43" src="https://user-images.githubusercontent.com/9341608/109168651-55dc8780-777f-11eb-87d8-4a49a2e03b84.png">

The `/` at the end should be added in deleteDir method of BunnyCDNAdapter class, but since the `fullPath` method doesn't get info about an object being a directory, it doesn't pass it along to `Util::normalizePath`, which has a condition to add `/` at the end of directory paths.

**Comment by jeremyj11** [comment]
Are you using the latest version?
Was fixed here https://github.com/PlatformCommunity/flysystem-bunnycdn/pull/7

**Comment by jedlikowski** [comment]
I am using v0.3.1 and composer doesn't report any new versions. Has this fix been released?

**Comment by sifex** [comment]
@jedlikowski I'll push one now for you

**Comment by sifex** [comment]
@jedlikowski Pushed v0.3.2, let me know if that doesn't work & please close when resolved 😄 

**Github:**
https://github.com/PlatformCommunity/flysystem-bunnycdn/releases/tag/v0.3.2

**Packagist:**
https://packagist.org/packages/platformcommunity/flysystem-bunnycdn#v0.3.2

**Comment by jedlikowski** [comment]
Looks like it works now, thanks! 😄
