### ISSUE TITLE
Upload progress goes so fast

### ISSUE THREAD

**Issue by Mohamed5550** [PlatformCommunity/flysystem-bunnycdn#80]
Hi

I am uploading a 16M file using Filament FilePond file uploader
I am uploading to bunny storage 

When I uplaoded the file it went to 100% in about 3 seconds, then it took about 5 mins to finish uploading

Thank in Advance, and thanks for the adapter

**Comment by tinect** [comment]
@Mohamed5550 how can we assist you? it might be a FilePond relevant topic for you.

**Comment by Mohamed5550** [comment]
Hi
I found it happens locally only, but on server it works fine

This is strange as in the two cases it uploads to bunny storage

But anyway thanks
